config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :tours, :users, :locations, :items, :groups, :transactions
  resources :shows do
    resources :counts, except:[:index, :show, :edit]
  end
  post '/shows/:id' => 'counts#create' #I can't seem to get the batch form working without this
  post 'notes/' => 'notes#create' #this is the endpoint for cloudmailin to send show notes
  get 'reports' => 'reports#index'
  get 'reports/summary' => 'reports#summary', :as => :summary_report
  get 'reports/by_sub' => 'reports#by_sub', :as => :by_sub_report
  get 'welcome/index'
  root 'welcome#index' 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @locations = Location.owned(current_user).count # has group set up their stuff?
    @items = Item.owned(current_user).count         # if not we'll tell them to in the view 
    @shows = Show.owned(current_user).count         #
    @tours = Tour.owned(current_user).count         #
    @counts = Show.owned(current_user).hascounts.count   # Have they counted anything in yet?
    @setup = (@locations > 0) && (@items > 0) && (@shows > 0) && (@tours > 0)
    if @setup #dont bother with queries unless we're ready for em
      if @counts > 0 # If they have, then lets pull the info on their latest shows, if they have one in progress, etc
        @latest = Show.owned(current_user).hascounts.order(date: :desc).first
        @outstanding = Item.counted_in(@latest) - Item.counted_out(@latest)
        if @outstanding.any?
          @primary = Location.prime(current_user) #only using it for label of the transfer button during a show, ie only if outstanding
        else
          @next = Show.owned(current_user).where("date > ?", @latest.date).order(:date).first #only needed if not outstanding
        end
      else 
        @next = Show.owned(current_user).order(:date).first #if they havent counted, what's going to be their first show?
      end
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  
  def showtime_link(show, text)
    if show
      link_to "#{text} Show: #{show.venue}" , show_path(show), :class=> 'btn btn-primary'
    end
  end
  
  def setup_links(object,text,place)
    if object == 0
      link_to "Setup #{text}", place, :class=> 'btn btn-primary'
    end
  end

end

app/views/welcome/index.html.erb
<h1>Welcome to MrchBox</h1>

<%= setup_links(@items, "Items", new_item_path) %>
<%= setup_links(@locations, "Locations", new_location_path) %>
<%= setup_links(@tours, "a Tour", new_tour_path) %>

<% if @setup %>
  <% if @outstanding.present? %>
      <%= "Show in progress at #{@latest.venue}!" %><br>
      <%= showtime_link(@latest,"View") %>
      <%= link_to 'Comp an Item', new_transaction_path(show:@latest.id, type:5), class: 'btn btn-default' %>
      <%= link_to "Transfer to #{@primary.name}", new_transaction_path(show:@latest.id, type:3), class: 'btn btn-default' %>
<%= link_to 'Count Out', new_show_count_path(@latest, direction:"out"), :class=> 'btn btn-default'  %>
    <% else %>
      <%= showtime_link(@latest,"Latest") %>
      <%= showtime_link(@next,"Next") %>
      <%= link_to "All Shows", shows_path, :class=> 'btn btn-default' %>    
<div class="btn-group">
   <button type="button" class="btn btn-default dropdown-toggle" 
      data-toggle="dropdown">
      Do Stuff <span class="caret"></span>
   </button>
   <ul class="dropdown-menu" role="menu">
     <li><%= link_to 'Add To Inventory', new_transaction_path(type:2) %></li>
      <li><%= link_to 'Non-Show Sale', new_transaction_path(type:1) %></li>
     <li><%= link_to 'Non-Show Comp', new_transaction_path(type:5) %></li>
     <li><%= link_to 'Transfer Stuff', new_transaction_path(type:3) %></li>
   </ul>
</div>
    <% end %>
<% end %>