config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :tours, :users, :locations, :items, :groups, :transactions
  resources :shows do
    resources :counts, except:[:index, :show, :edit]
  end
  post '/shows/:id' => 'counts#create' #I can't seem to get the batch form working without this
  post 'notes/' => 'notes#create' #this is the endpoint for cloudmailin to send show notes
  get 'reports' => 'reports#index'
  get 'reports/summary' => 'reports#summary', :as => :summary_report
  get 'reports/by_sub' => 'reports#by_sub', :as => :by_sub_report
  get 'welcome/index'
  root 'welcome#index' 

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  include Ownable
  has_many :shows, :dependent => :destroy
  has_many :transactions, :through => :shows
  accepts_nested_attributes_for :shows
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tours = Tour.owned(current_user)
    respond_with(@tours)
  end

  def show
    @shows = Show.owned(current_user).ontour(@tour)
  end

  def new
    @tour = Tour.new
  end

  def edit
  end

  def create
    @tour = Tour.new(tour_params)
    @tour.save
    redirect_to tour_path(@tour)
  end

  def update
    @tour.update(tour_params)
    respond_with(@tour)
  end

  def destroy
    @tour.destroy
    respond_with(@tour)
  end

  private
    def set_tour
      @tour = Tour.find(params[:id])
      check_user(@tour.group_id)
    end

    def tour_params
      params.require(:tour).permit(:name,shows_attributes: [:id,:date,:venue,:city,:_destroy]).merge(group_id: current_user.group_id)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
<%= f.fields_for :shows do|show| %>
      <%= render 'show_fields', :f => show %><br>
<% end %><br>
<div>
      <%= link_to_add_association 'add show', f, :shows %>
</div><br>
  <div class="field">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/tours/_show_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div></div><br>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>Listing tours</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.name %></td>
        <td><%= tour.group.name %></td>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
</p>

<% @shows.each do |show| %>
<%= link_to "#{show.date.to_s(:short)} #{show.venue}", show_path(show) %><br>
<% end %>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>