config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :tours, :users, :locations, :items, :groups, :transactions
  resources :shows do
    resources :counts, except:[:index, :show, :edit]
  end
  post '/shows/:id' => 'counts#create' #I can't seem to get the batch form working without this
  post 'notes/' => 'notes#create' #this is the endpoint for cloudmailin to send show notes
  get 'reports' => 'reports#index'
  get 'reports/summary' => 'reports#summary', :as => :summary_report
  get 'reports/by_sub' => 'reports#by_sub', :as => :by_sub_report
  get 'welcome/index'
  root 'welcome#index' 

end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :counts, :dependent => :destroy
  has_many :guests, :dependent => :destroy
  has_many :transactions
  belongs_to :tour
  accepts_nested_attributes_for :guests, allow_destroy: true, :reject_if => :all_blank
  scope :owned, ->(user) { joins(:tour).where(tours:{group_id:user.group_id}) }
  scope :hascounts, -> { joins(:counts).where("counts.quantity > 0").uniq.order(date: :desc) }
  scope :ontour, ->(tour) {where(tour_id:tour.id)}
  scope :relevant, -> {where("date >= ? ", Date.today - 7)}
  scope :irrelevant, -> {where("date < ? ", Date.today - 7)}
  
  def dateandvenue
    "#{date} #{venue}"
  end

  
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  #http_basic_authenticate_with :name => "user", :password => "mypass", :only => :incoming
  
  def index
    @shows = Show.owned(current_user).relevant
    @older = Show.owned(current_user).irrelevant
  end

  def show
    @show = Show.find(params[:id])
    check_user(@show.tour.group_id)
    @guests = Guest.where(show_id:params[:id])
    @guestlist = @guests.collect do |guest|
      guest.name
    end
    @countins = Count.where(show_id:@show.id, out:false).includes(:item)
    @latest = Show.owned(current_user).hascounts.maximum(:date)
    @islatest = @latest.present? ? @latest <= @show.date : true 
    @total = 0
        @stots = 0
    if @islatest #only need this junk if show is eligible for counts
      @in_items = @countins.pluck(:item_id) 
      @needins = Item.owned(current_user).active.pluck(:id) - @in_items 
      if @countins.present? #if nothing's been counted in, then we can't count anything out. Verify that present works
        @needouts = @in_items - Item.counted_out(@show).pluck(:id) 
        @primary = Location.prime(current_user)
        
      end
    end
  end

  def new
    @show = Show.new
    @tours = Tour.where(:group_id => current_user.group_id)
  end

  def edit
    @tours = Tour.where(:group_id => current_user.group_id)
    if @show.guests.blank?
      @show.guests.build
    end
  end

  def create
    @show = Show.new(show_params)
    @show.save
    redirect_to action: 'index'
  end

  def update
    @show.update(show_params)
    redirect_to show_path(@show)
  end

  def destroy
    @show.destroy
    redirect_to action:"index"
  end

  private
    def set_show
      @show = Show.find(params[:id])
      check_user(@show.tour.group_id)
    end

    def show_params
      params.require(:show).permit(:date, :venue, :city, :tour_id,:notes, guests_attributes:[:id,:name,:plus,:special,:_destroy])
    end
  
  #def incoming_params
   # params.require(envelope:[:from]).permit(headers:['Subject'],:plain)
 # end
  
end

app/helpers/shows_helper.rb
module ShowsHelper
  
  def show_guests
    if @guests.count > 0
      link_to pluralize((@guests.count + @guests.sum(:plus)),"guest"), "#", rel:"popover", :"data-toggle"=>"popover", :"title"=>"#{current_user.group.name} Guests #{@show.date.strftime("%-m/%-d")}", :"data-content"=> "#{render 'guestlist'}" 
    else
    link_to "Add Guests", edit_show_path(component:"guests")
    end
  end
  
  def show_notes
    if @show.notes.blank?
      link_to "Add Notes", edit_show_path(component:"notes"), class:"btn btn-primary"
    else
      render 'notes'
    end
  end

  def show_count
    if @islatest && @countins.blank? && @needins.present?
      link_to 'Count In', new_show_count_path(@show, direction:"in"), :class=> 'btn btn-primary'
    elsif @islatest && @needouts.present?
      link_to 'Count Out', new_show_count_path(@show, direction:"out"), :class=> 'btn btn-primary'
    end
  end

end

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.collection_select :tour_id, @tours, :id, :name %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_guest_fields.html.erb
<div class="form-inline">
  <div class="nested-fields">
  <div class="form-group">
    <%= f.text_field :name, class:"form-control", placeholder:"name" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">+</label>
    <%= f.number_field :plus, class:"form-control", placeholder:"+" %>
  </div>
  <div class="form-group">
    <%= f.text_field :special, class:"form-control", placeholder:"access" %>
  </div>
   <%= link_to_remove_association 'remove guest', f, class:"btn btn-default" %>
</div><br>
  </div>
  

app/views/shows/_guest_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= @show.venue %>
<%= f.fields_for :guests do|guest| %>

<%= render 'guest_fields', :f => guest %>

<% end %>

<div>
  <%= link_to_add_association 'add guest', f, :guests %>
</div><br>
  <div class="field">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/shows/_guestlist.html.erb
<% @guests.each do |guest| %>
<%= guest.plus ? "#{guest.name} +#{guest.plus} #{guest.special}" : "#{guest.name} #{guest.special}"%><br>
<% end %>
<br>
<%= link_to "Edit Guestlist", edit_show_path(component:"guests") %>

app/views/shows/_notes.html.erb
  <!-- Button trigger modal -->
  <button class="btn btn-primary" data-toggle="modal" data-target="#notes">
    View notes
  </button>

  <!-- Modal -->
  <div class="modal fade" id="notes" tabindex="-1" role="dialog" aria-labelledby="todo--label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="todo--label">Notes <%= link_to '  <span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_show_path(component:"notes") %></h4>
        </div>
        <div class="modal-body">
          <%= simple_format(@show.notes) %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>   

app/views/shows/_notes_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
<div class="col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3">
<form role="form">
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class:"form-control input-lg" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/shows/edit.html.erb
<% if params[:component] == "guests" %>
<%= render 'guest_form' %>
<% elsif params[:component] == "notes" %>
<%= render 'notes_form' %>
<% else %>
<%= render 'form' %>
<% end %>
<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h2>Recent and Upcoming Shows</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Venue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shows.each do |show| %>
      <tr>
        <td><%= show.date %></td>
        <td><%= show.venue %></td>
        <td><%= link_to 'Showtime', show_path(show) %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Show', new_show_path, class:"btn btn-default" %>
<% if @older.present? %>
<br><br>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<div >
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Show Old Shows
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Venue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @older.each do |show| %>
      <tr>
        <td><%= show.date %></td>
        <td><%= show.venue %></td>
        <td><%= link_to 'Showtime', show_path(show) %></td>
        <td><%= link_to 'Edit', edit_show_path(show) %></td>
        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>        
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<h2><%= @show.date.strftime("%e %b") %> - <%= @show.venue %></h2>
<h3><%= @show.city %>  <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_show_path(@show) %></h3>
<h4><%= link_to "#{@show.tour.name} Tour", tour_path(@show.tour) %> - <%= show_guests %></h4>
<%= show_count %>
<% if @islatest && @needouts.present? %>
<div class="btn-group">
   <button type="button" class="btn btn-primary dropdown-toggle" 
      data-toggle="dropdown">
      Do Stuff <span class="caret"></span>
   </button>
   <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Comp Item', new_transaction_path(show:@show.id,type:5) %></li>
     <li><%= link_to "Transfer to #{@primary.name}", new_transaction_path(show:@show.id,type:3) %></li>
     <% if @needins.present? %>
     <li class="divider"></li><li><%=link_to 'Count In More Stuff', show_new_count_path(@show, direction:"in") %></li>
     <% end %>
   </ul>
</div>  
<% end %>
<%= show_notes %>
<br><br>
  
<% if @countins.present? %>
<div class="table-responsive">
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>In</th>
      <th>Added</th>
      <th>Comps</th>
      <th>Out</th>
      <th>Price</th>
      <th>Sales</th>
      <th>Gross</th>
    </tr>
  </thead>

  <tbody>
    <% total = 0 %>
    <% @countins.each do |count| %>
      <tr>        
        <td><%= count.item.name_with_sub %></td>path
        <td><%= i = count.quantity %>
            <% if !count.find_out && @islatest %>
          <%= link_to '<span class="glyphicon glyphicon-remove danger"></span>'.html_safe, show_count_path(@show,count), method: :delete, class: 'alert-danger', data: { confirm: "Are you sure you want to re-count in #{count.item.name_with_sub}?" } %>
            <% end %>
        </td>
        <td><%= t = count.item.find_transfers(@show) > 0 ? count.item.find_transfers(@show) : "-" %></td>
        <td><%= c = count.item.find_comps(@show) > 0 ? count.item.find_comps(@show) : "-" %></td>
        <td><%= o = count.find_out ? count.find_out.quantity : "-" %>
            <% if count.find_out && @islatest %>
          <%= link_to '<span class="glyphicon glyphicon-repeat"></span>'.html_safe, show_count_path(@show,count.find_out), method: :delete, data: { confirm: "Are you sure you want to re-count out #{count.item.name_with_sub}?" } %>
            <% end %></td>
        <td>$<%= r = count.rate %></td>
        <% if o.is_a? Integer %>
        <td><%= s = (i - o.to_i - c.to_i + t.to_i) %></td>
        <td>$<%= cash = s*r %></td>
        <% else %>
        <td>-</td>
        <td>-</td>
        <% end %>
        <% @total += cash.to_i %>
        <% if count.item.soft %>        
        <% @stots += cash.to_i %>
        <% else %>
        <% @stots %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% if @needouts.blank? %>
<h3>Soft: $<%= @stots %></h3>
<h3>Total: $<%= @total %></h3>
<% end %>
<% end %>
<br>